USE sakila;
-- Write SQL queries to perform the following tasks using the Sakila database:
-- 1. List the number of films per category.
SELECT
	c.name AS category_name,
    COUNT(fc.film_id) AS number_of_films
FROM category AS c
JOIN film_category AS fc
	ON c.category_id = fc.category_id
GROUP BY c.category_id, c.name
ORDER BY number_of_films DESC;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT
	s.store_id,
    ci.city,
    co.country
FROM store AS s
JOIN address as a
	ON s.address_id = a.address_id
JOIN city AS ci
	ON a.city_id = ci.city_id
JOIN country AS co
	ON ci.country_id = co.country_id;
    
-- 3. Calculate the total revenue generated by each store in dollars.
SELECT 
	i.store_id,
    SUM(p.amount) AS total_revenue
FROM payment as p
JOIN rental as r
	ON p.rental_id = r.rental_id
JOIN inventory as i
	ON r.inventory_id = i.inventory_id
GROUP BY i.store_id
ORDER BY total_revenue DESC;

-- 4. Determine the average running time of films for each category.
SELECT
    c.name,
    AVG(f.length) AS avg_running_time
FROM category AS c
JOIN film_category AS fc ON c.category_id = fc.category_id
JOIN film AS f ON fc.film_id = f.film_id
GROUP BY c.category_id, c.name;

-- 5. Identify the film categories with the longest average running time.
SELECT
	c.name,
    AVG(f.length) AS avg_running_time
FROM category AS c
JOIN film_category AS fc
	ON c.category_id = fc.category_id
JOIN film AS f
	ON fc.film_id = f.film_id
GROUP BY c.category_id, c.name
ORDER BY avg_running_time DESC; 

-- 6. Display the top 10 most frequently rented movies in descending order.
SELECT
    f.title,
    COUNT(r.rental_id) AS rental_count
FROM rental AS r
JOIN inventory AS i
    ON r.inventory_id = i.inventory_id
JOIN film AS f
    ON i.film_id = f.film_id
GROUP BY f.film_id, f.title
ORDER BY rental_count DESC
LIMIT 10;


-- 7. Determine if "Academy Dinosaur" can be rented from Store 1.
SELECT
	f.title,
    i.store_id
FROM film AS f
JOIN inventory AS i
	on f.film_id = i.film_id
WHERE f.title = 'Academy Dinosaur'
	AND i.store_id = 1;

-- 8. Provide a list of all distinct film titles, along with their availability status in the inventory. Include a column indicating whether each title is 'Available' or 
-- 'NOT available.' Note that there are 42 titles that are not in the inventory, and this information can be obtained using a CASE statement combined with IFNULL."
SELECT
    f.title,
    CASE
        WHEN COUNT(i.inventory_id) = 0 THEN 'NOT available'
        ELSE 'Available'
    END AS availability_status
FROM film AS f
LEFT JOIN inventory AS i
    ON f.film_id = i.film_id
GROUP BY f.film_id, f.title
ORDER BY f.title;

